#!/bin/bash

###########################
##
## IPtables / Netfilter script
##
###########################


PATH='/sbin'

if [[ $1 = "" ]]; then

	iptables -L

fi


if [[ $1 = 'up' ]]; then

	# Flush the tables to apply changes
	iptables -F

	# Default policy to drop 'everything' but our output to internet
	iptables -P FORWARD DROP
	iptables -P INPUT DROP
	iptables -P OUTPUT ACCEPT

	# Allow established connection (the responses to our outgoing traffic)
	iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

	# Allow local proramsthat use loopback (Unix sockest)
	iptables -A INPUT -s 127.0.0.0/8 -d 127.0.0.0/8 -i lo -j ACCEPT

	# Allow incoming traffic on defined ports
	iptables -A INPUT -p tcp --dport 22 -m state --state NEW -j ACCEPT

	# Deny everyone from connecting to port 6973
	iptables -A INPUT -p tcp --dport 6973 -j REJECT

fi

if [[ $1 = 'down' ]]; then

	iptables -F

fi
